dbt-local-agent:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: dbt-local-agent.duckdb
      threads: 4
    prod:
      type: duckdb
      path: dbt-local-agent_prod.duckdb
      threads: 8
